language: python
python: 2.7
env:
  - TOX_ENV=py2.6-django1.6.1
  - TOX_ENV=py2.7-django1.6.1
  - TOX_ENV=py2.6-django1.5.5
  - TOX_ENV=py2.7-django1.5.5
  - TOX_ENV=py2.6-django1.4.10
  - TOX_ENV=py2.7-django1.4.10
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
